// Generated by scripts/build-apps-script.mjs from src/core. Do not edit by hand; run `npm run build:apps-script`.
// Paste into the Apps Script project as GmailSendCore.gs next to Api.gs, GmailAdapter.gs, Drafting.gs and Setup.gs.
"use strict";
var GmailSendCore = (() => {
  var __defProp = Object.defineProperty;
  var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
  var __getOwnPropNames = Object.getOwnPropertyNames;
  var __hasOwnProp = Object.prototype.hasOwnProperty;
  var __export = (target, all) => {
    for (var name in all)
      __defProp(target, name, { get: all[name], enumerable: true });
  };
  var __copyProps = (to, from, except, desc) => {
    if (from && typeof from === "object" || typeof from === "function") {
      for (let key of __getOwnPropNames(from))
        if (!__hasOwnProp.call(to, key) && key !== except)
          __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
    }
    return to;
  };
  var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

  // src/core/browser.ts
  var browser_exports = {};
  __export(browser_exports, {
    DEFAULT_TIMEZONE: () => DEFAULT_TIMEZONE,
    GMAIL_BLOCKQUOTE_OPEN: () => GMAIL_BLOCKQUOTE_OPEN,
    GMAIL_SIGNATURE_PREFIX: () => GMAIL_SIGNATURE_PREFIX,
    GMAIL_WRAP_WIDTH: () => GMAIL_WRAP_WIDTH,
    NNBSP: () => NNBSP,
    addressText: () => addressText,
    attributionHtml: () => attributionHtml,
    attributionText: () => attributionText,
    bareSubject: () => bareSubject,
    base64Decode: () => base64Decode,
    base64Encode: () => base64Encode,
    base64Url: () => base64Url,
    buildMime: () => buildMime,
    composeForward: () => composeForward,
    composeNew: () => composeNew,
    composeReply: () => composeReply,
    dateTimeFormatter: () => dateTimeFormatter,
    decodeEntities: () => decodeEntities,
    decodeQuotedPrintable: () => decodeQuotedPrintable,
    displayName: () => displayName,
    encodeHeaderText: () => encodeHeaderText,
    escapeAttr: () => escapeAttr,
    escapeHtml: () => escapeHtml,
    formatAddress: () => formatAddress,
    formatAddressList: () => formatAddressList,
    formatGmailDateTime: () => formatGmailDateTime,
    formatRfc2822Date: () => formatRfc2822Date,
    forwardHeaderHtml: () => forwardHeaderHtml,
    forwardHeaderText: () => forwardHeaderText,
    forwardSubject: () => forwardSubject,
    fromBase64Url: () => fromBase64Url,
    gmailBoundary: () => gmailBoundary,
    gmailMessageId: () => gmailMessageId,
    headerValue: () => headerValue,
    htmlToText: () => htmlToText,
    linkify: () => linkify,
    looksLikeHtml: () => looksLikeHtml,
    neutralizeUnbalancedTags: () => neutralizeUnbalancedTags,
    normalizeNewlines: () => normalizeNewlines,
    parseAddress: () => parseAddress,
    parseAddressList: () => parseAddressList,
    quoteText: () => quoteText,
    quotedPrintable: () => quotedPrintable,
    randomAlnum: () => randomAlnum,
    randomHex: () => randomHex,
    replyRecipients: () => replyRecipients,
    replySubject: () => replySubject,
    rfc2822Formatter: () => rfc2822Formatter,
    sameEmail: () => sameEmail,
    setDateTimeFormatter: () => setDateTimeFormatter,
    setRfc2822Formatter: () => setRfc2822Formatter,
    signatureText: () => signatureText,
    textToGmailHtml: () => textToGmailHtml,
    tidyText: () => tidyText,
    unfoldHeaderValue: () => unfoldHeaderValue,
    uniqueAddresses: () => uniqueAddresses,
    utf8Decode: () => utf8Decode,
    utf8Encode: () => utf8Encode,
    withoutAddresses: () => withoutAddresses,
    wrapForwardedOriginal: () => wrapForwardedOriginal,
    wrapLine: () => wrapLine,
    wrapLinkedAddressLine: () => wrapLinkedAddressLine,
    wrapText: () => wrapText
  });

  // src/core/address.ts
  function unfoldHeaderValue(raw) {
    return raw.replace(/\r?\n[ \t]+/g, " ").replace(/[\r\n]+/g, " ");
  }
  function parseAddress(raw) {
    const s = unfoldHeaderValue(raw).trim();
    const m = s.match(/^(?:"([^"]*)"|([^<]*?))\s*<([^>]+)>$/);
    if (m) {
      const name = (m[1] ?? m[2] ?? "").trim();
      return name ? { name, email: m[3].trim() } : { email: m[3].trim() };
    }
    return { email: s.replace(/^<|>$/g, "").trim() };
  }
  function parseAddressList(rawInput) {
    if (!rawInput) return [];
    const raw = unfoldHeaderValue(rawInput);
    const out = [];
    let cur = "";
    let inQuote = false;
    let depth = 0;
    for (const ch of raw) {
      if (ch === '"') inQuote = !inQuote;
      else if (!inQuote && ch === "<") depth++;
      else if (!inQuote && ch === ">") depth = Math.max(0, depth - 1);
      if (ch === "," && !inQuote && depth === 0) {
        out.push(cur);
        cur = "";
      } else {
        cur += ch;
      }
    }
    if (cur.trim()) out.push(cur);
    return out.map((s) => s.trim()).filter(Boolean).map(parseAddress);
  }
  function formatAddress(a) {
    if (!a.name) return a.email;
    const needsQuote = /[^\w\s.'\-]/.test(a.name);
    const name = needsQuote ? `"${a.name.replace(/"/g, '\\"')}"` : a.name;
    return `${name} <${a.email}>`;
  }
  function formatAddressList(list) {
    return list.map(formatAddress).join(", ");
  }
  function addressText(a) {
    return a.name ? `${a.name} <${a.email}>` : `<${a.email}>`;
  }
  function sameEmail(a, b) {
    const ea = (typeof a === "string" ? a : a.email).trim().toLowerCase();
    const eb = (typeof b === "string" ? b : b.email).trim().toLowerCase();
    return ea === eb;
  }
  function uniqueAddresses(list) {
    const seen = /* @__PURE__ */ new Set();
    const out = [];
    for (const a of list) {
      const key = a.email.trim().toLowerCase();
      if (!key || seen.has(key)) continue;
      seen.add(key);
      out.push(a);
    }
    return out;
  }
  function withoutAddresses(list, exclude) {
    return list.filter((a) => !exclude.some((e) => sameEmail(a, e)));
  }
  function displayName(a) {
    return a.name?.trim() || a.email;
  }

  // src/core/wrap.ts
  var GMAIL_WRAP_WIDTH = 72;
  function wrapLine(line, width = GMAIL_WRAP_WIDTH) {
    if (line.length <= width) return [line];
    const words = line.split(" ");
    const out = [];
    let cur = "";
    for (const w of words) {
      if (cur === "") {
        cur = w;
        continue;
      }
      if (cur.length + 1 + w.length <= width) cur += " " + w;
      else {
        out.push(cur);
        cur = w;
      }
    }
    if (cur !== "") out.push(cur);
    return out;
  }
  function wrapText(text, width = GMAIL_WRAP_WIDTH) {
    return normalizeNewlines(text).split("\n").flatMap((l) => wrapLine(l.replace(/\s+$/, ""), width)).join("\n");
  }
  function normalizeNewlines(s) {
    return s.replace(/\r\n?/g, "\n");
  }
  function quoteText(text) {
    return normalizeNewlines(text).split("\n").map((l) => {
      if (l === "") return ">";
      if (l.startsWith(">")) return ">" + l;
      return "> " + l;
    }).join("\n");
  }
  function tidyText(text) {
    return normalizeNewlines(text).split("\n").map((l) => l.replace(/[ \t]+$/, "")).join("\n").replace(/\n{3,}/g, "\n\n").trim();
  }

  // src/core/html.ts
  function escapeHtml(s) {
    return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/'/g, "&#39;");
  }
  function escapeAttr(s) {
    return escapeHtml(s).replace(/"/g, "&quot;");
  }
  var VOID_ELEMENTS = /* @__PURE__ */ new Set(["area", "base", "br", "col", "embed", "hr", "img", "input", "link", "meta", "param", "source", "track", "wbr"]);
  function neutralizeUnbalancedTags(html) {
    const stack = [];
    let out = "";
    let last = 0;
    const re = /<\/?([a-zA-Z][a-zA-Z0-9]*)\b[^>]*>/g;
    let m;
    while (m = re.exec(html)) {
      out += html.slice(last, m.index);
      last = m.index + m[0].length;
      const tag = m[1].toLowerCase();
      const closing = m[0].startsWith("</");
      if (VOID_ELEMENTS.has(tag) || /\/>$/.test(m[0])) {
        out += m[0];
        continue;
      }
      if (!closing) {
        stack.push(tag);
        out += m[0];
        continue;
      }
      const idx = stack.lastIndexOf(tag);
      if (idx === -1) out += m[0].replace(/</g, "&lt;").replace(/>/g, "&gt;");
      else {
        stack.length = idx;
        out += m[0];
      }
    }
    out += html.slice(last);
    for (let i = stack.length - 1; i >= 0; i--) out += `</${stack[i]}>`;
    return out;
  }
  var NAMED_ENTITIES = {
    amp: "&",
    lt: "<",
    gt: ">",
    quot: '"',
    apos: "'",
    nbsp: "\xA0",
    ndash: "\u2013",
    mdash: "\u2014",
    hellip: "\u2026",
    rsquo: "\u2019",
    lsquo: "\u2018",
    rdquo: "\u201D",
    ldquo: "\u201C",
    copy: "\xA9",
    reg: "\xAE",
    trade: "\u2122",
    bull: "\u2022",
    middot: "\xB7"
  };
  function decodeEntities(s) {
    return s.replace(/&(#x[0-9a-f]+|#\d+|[a-z]+);/gi, (m, body) => {
      if (body[0] === "#") {
        const code = body[1].toLowerCase() === "x" ? parseInt(body.slice(2), 16) : parseInt(body.slice(1), 10);
        if (!Number.isFinite(code) || code < 0 || code > 1114111) return m;
        return String.fromCodePoint(code);
      }
      const v = NAMED_ENTITIES[body.toLowerCase()];
      return v ?? m;
    });
  }
  var URL_RE = /((?:https?:\/\/|www\.)[^\s<>"]+)/gi;
  var EMAIL_RE = /([\w.+-]+@[\w-]+(?:\.[\w-]+)+)/g;
  function linkify(escaped) {
    const pieces = [];
    let last = 0;
    for (const m of escaped.matchAll(URL_RE)) {
      const start = m.index ?? 0;
      pieces.push(linkifyEmails(escaped.slice(last, start)));
      let url = m[1];
      let trail = "";
      const t = url.match(/[.,;:!?)\]]+$/);
      if (t) {
        trail = t[0];
        url = url.slice(0, -trail.length);
      }
      const href = /^www\./i.test(url) ? `http://${url}` : url;
      pieces.push(`<a href="${href}" target="_blank">${url}</a>${trail}`);
      last = start + m[1].length;
    }
    pieces.push(linkifyEmails(escaped.slice(last)));
    return pieces.join("");
  }
  function linkifyEmails(s) {
    return s.replace(EMAIL_RE, (addr) => `<a href="mailto:${addr}" target="_blank">${addr}</a>`);
  }
  function textToGmailHtml(text, mode = "new") {
    const body = normalizeNewlines(text).replace(/^\n+/, "").replace(/\s+$/, "");
    if (body === "") return mode === "reply" ? "" : "<div><br></div>";
    const parts = body.split("\n").map((l) => l.trim() === "" ? "<br>" : linkify(escapeHtml(l)));
    if (mode === "reply") {
      const [first, ...rest] = parts;
      const head = first === "<br>" ? "<div><br></div>" : first;
      return head + rest.map((p) => `<div>${p}</div>`).join("");
    }
    return parts.map((p) => `<div>${p}</div>`).join("");
  }
  var BLOCK_TAGS = /* @__PURE__ */ new Set([
    "div",
    "p",
    "tr",
    "li",
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6",
    "blockquote",
    "pre",
    "ul",
    "ol",
    "table",
    "hr",
    "address",
    "section",
    "article",
    "header",
    "footer",
    "dd",
    "dt"
  ]);
  function htmlToText(html) {
    let src = html.replace(/<!--[\s\S]*?-->/g, "").replace(/<(script|style|head|title)\b[^>]*>[\s\S]*?<\/\1>/gi, "");
    let out = "";
    const linkStack = [];
    let listStack = [];
    let inPre = false;
    const ensureNewline = () => {
      if (out.length && !out.endsWith("\n")) out += "\n";
    };
    const ensureBlank = () => {
      ensureNewline();
      if (!out.endsWith("\n\n")) out += "\n";
    };
    const tagRe = /<\/?([a-zA-Z][a-zA-Z0-9]*)\b([^>]*)>/g;
    let idx = 0;
    let m;
    while (m = tagRe.exec(src)) {
      const textChunk = src.slice(idx, m.index);
      out += renderText(textChunk, inPre);
      idx = m.index + m[0].length;
      const raw = m[0];
      const tag = m[1].toLowerCase();
      const attrs = m[2] ?? "";
      const closing = raw.startsWith("</");
      if (tag === "br") {
        out += "\n";
        continue;
      }
      if (tag === "img") {
        const alt = getAttr(attrs, "alt");
        if (alt) out += `[image: ${decodeEntities(alt).trim()}]`;
        continue;
      }
      if (tag === "a") {
        if (!closing) {
          linkStack.push({ href: decodeEntities(getAttr(attrs, "href") ?? ""), start: out.length });
        } else {
          const link = linkStack.pop();
          if (link) {
            const content = out.slice(link.start);
            out = out.slice(0, link.start) + renderLink(content, link.href);
          }
        }
        continue;
      }
      if (tag === "pre") {
        inPre = !closing;
        closing ? ensureNewline() : ensureNewline();
        continue;
      }
      if (tag === "ul" || tag === "ol") {
        if (!closing) {
          listStack.push({ ordered: tag === "ol", n: 0 });
          ensureNewline();
        } else {
          listStack.pop();
          ensureNewline();
        }
        continue;
      }
      if (tag === "li") {
        if (!closing) {
          ensureNewline();
          const l = listStack[listStack.length - 1];
          if (l) {
            l.n++;
            out += l.ordered ? `   ${l.n}. ` : "   - ";
          } else out += "   - ";
        } else ensureNewline();
        continue;
      }
      if (tag === "td" || tag === "th") {
        if (closing) {
          if (out.length && !out.endsWith("\n") && !out.endsWith(" ")) out += " ";
        }
        continue;
      }
      if (tag === "p") {
        closing ? ensureBlank() : ensureBlank();
        continue;
      }
      if (BLOCK_TAGS.has(tag)) {
        ensureNewline();
        continue;
      }
    }
    out += renderText(src.slice(idx), inPre);
    return out.split("\n").map((l) => l.replace(/[ \t ]+$/, "").replace(/^[ \t ]+(?=\S)/, (s) => s.length >= 3 ? s : "")).join("\n").replace(/\n{3,}/g, "\n\n").trim();
  }
  function renderText(chunk, inPre) {
    if (!chunk) return "";
    let t = decodeEntities(chunk);
    if (inPre) return t;
    t = t.replace(/[\s ]+/g, " ");
    return t;
  }
  function renderLink(content, href) {
    const text = content.trim();
    let shown = href.trim();
    if (!shown) return content;
    if (/^mailto:/i.test(shown)) shown = shown.replace(/^mailto:/i, "").split("?")[0];
    else if (/^tel:/i.test(shown)) shown = shown.replace(/^tel:/i, "");
    if (!text) return `<${shown}>`;
    if (text.toLowerCase() === shown.toLowerCase()) return content;
    const stripped = shown.replace(/^https?:\/\//i, "").replace(/\/$/, "");
    if (text.toLowerCase() === stripped.toLowerCase()) return content;
    const lead = content.match(/^\s*/)?.[0] ?? "";
    const trail = content.match(/\s*$/)?.[0] ?? "";
    return `${lead}${text} <${shown}>${trail}`;
  }
  function getAttr(attrs, name) {
    const re = new RegExp(`\\b${name}\\s*=\\s*(?:"([^"]*)"|'([^']*)'|([^\\s>]+))`, "i");
    const m = attrs.match(re);
    if (!m) return void 0;
    return m[1] ?? m[2] ?? m[3];
  }
  function looksLikeHtml(s) {
    return /<[a-z][\s\S]*>/i.test(s);
  }

  // src/core/attribution.ts
  var DEFAULT_TIMEZONE = "America/New_York";
  var NNBSP = "\u202F";
  var dateTimeFormatter = null;
  function setDateTimeFormatter(fn) {
    dateTimeFormatter = fn;
  }
  function formatGmailDateTime(date, opts = {}) {
    const timeZone = opts.timeZone ?? DEFAULT_TIMEZONE;
    const sep = opts.amPmSeparator ?? NNBSP;
    if (dateTimeFormatter) {
      const p = dateTimeFormatter(date, timeZone);
      return `${p.weekday}, ${p.month} ${p.day}, ${p.year} at ${p.hour}:${p.minute}${sep}${p.dayPeriod}`;
    }
    const parts = new Intl.DateTimeFormat("en-US", {
      weekday: "short",
      month: "short",
      day: "numeric",
      year: "numeric",
      hour: "numeric",
      minute: "2-digit",
      hour12: true,
      timeZone
    }).formatToParts(date);
    const get = (type) => parts.find((p) => p.type === type)?.value ?? "";
    return `${get("weekday")}, ${get("month")} ${get("day")}, ${get("year")} at ${get("hour")}:${get("minute")}${sep}${get("dayPeriod")}`;
  }
  function wrapLinkedAddressLine(line, width = GMAIL_WRAP_WIDTH) {
    const tokens = [];
    for (const w of line.split(" ")) {
      if (w.length > 1 && w.startsWith("<")) {
        tokens.push({ s: "<", glue: true });
        tokens.push({ s: w.slice(1), glue: false });
      } else tokens.push({ s: w, glue: false });
    }
    const lines = [];
    let cur = "";
    let prevGlue = false;
    for (const t of tokens) {
      const sep = cur === "" || prevGlue ? "" : " ";
      if (cur !== "" && cur.length + sep.length + t.s.length > width) {
        lines.push(cur);
        cur = t.s;
      } else cur += sep + t.s;
      prevGlue = t.glue;
    }
    if (cur !== "") lines.push(cur);
    return lines.join("\n");
  }
  function attributionText(original, opts = {}) {
    const line = `On ${formatGmailDateTime(original.date, opts)} ${addressText(original.from)} wrote:`;
    if (line.length <= GMAIL_WRAP_WIDTH) return line;
    if (opts.linkifyEmail) return wrapLinkedAddressLine(line);
    return line.replace(/ wrote:$/, "\nwrote:");
  }
  function attributionHtml(original, opts = {}) {
    const from = original.from;
    const email = opts.linkifyEmail ? `&lt;<a href="mailto:${escapeAttr(from.email)}" target="_blank">${escapeHtml(from.email)}</a>&gt;` : `&lt;${escapeHtml(from.email)}&gt;`;
    const who = from.name ? `${escapeHtml(from.name)} ${email}` : email;
    return `On ${escapeHtml(formatGmailDateTime(original.date, opts))} ${who} wrote:`;
  }
  function linkedEmail(email) {
    return `&lt;<a href="mailto:${escapeAttr(email)}">${escapeHtml(email)}</a>&gt;`;
  }
  function recipientListHtml(list) {
    return list.map((a) => a.name ? `${escapeHtml(a.name)} ${linkedEmail(a.email)}` : linkedEmail(a.email)).join(", ");
  }
  function forwardHeaderHtml(original, opts = {}) {
    const from = original.from;
    const fromHtml = from.name ? `<strong class="gmail_sendername" dir="auto">${escapeHtml(from.name)}</strong> <span dir="auto">${linkedEmail(from.email)}</span>` : `<span dir="auto">${linkedEmail(from.email)}</span>`;
    let s = `---------- Forwarded message ---------<br>From: ${fromHtml}<br>Date: ${escapeHtml(formatGmailDateTime(original.date, opts))}<br>Subject: ${escapeHtml(original.subject)}<br>To: ${recipientListHtml(original.to)}<br>`;
    if (original.cc.length) s += `Cc: ${recipientListHtml(original.cc)}<br>`;
    return s;
  }
  function forwardHeaderText(original, opts = {}) {
    const lines = [
      "---------- Forwarded message ---------",
      `From: ${addressText(original.from)}`,
      `Date: ${formatGmailDateTime(original.date, opts)}`,
      `Subject: ${original.subject}`,
      `To: ${original.to.map(addressText).join(", ")}`
    ];
    if (original.cc.length) lines.push(`Cc: ${original.cc.map(addressText).join(", ")}`);
    return lines.map((l) => wrapLinkedAddressLine(l)).join("\n");
  }

  // src/core/subject.ts
  function replySubject(subject) {
    const s = subject.trim();
    if (s === "") return "Re:";
    return /^re:/i.test(s) ? s : `Re: ${s}`;
  }
  function forwardSubject(subject) {
    const s = subject.trim();
    if (s === "") return "Fwd:";
    return /^(fwd?|fw):/i.test(s) ? s : `Fwd: ${s}`;
  }
  function bareSubject(subject) {
    return subject.replace(/^(\s*(re|fwd?|fw)\s*:\s*)+/i, "").trim();
  }

  // src/core/recipients.ts
  function replyRecipients(original, myEmails2, replyAll) {
    const isMe = (a) => myEmails2.some((m) => sameEmail(a, m));
    const fromMe = isMe(original.from);
    if (fromMe) {
      const to2 = uniqueAddresses(original.to);
      const cc2 = replyAll ? withoutAddresses(uniqueAddresses(original.cc), to2) : [];
      return { to: to2, cc: cc2 };
    }
    const primary = original.replyTo?.length ? original.replyTo : [original.from];
    if (!replyAll) return { to: uniqueAddresses(primary), cc: [] };
    const to = uniqueAddresses([...primary, ...original.to]).filter((a) => !isMe(a));
    const cc = uniqueAddresses(original.cc).filter((a) => !isMe(a) && !to.some((t) => sameEmail(t, a)));
    return { to, cc };
  }

  // src/core/compose.ts
  var GMAIL_BLOCKQUOTE_OPEN = '<blockquote class="gmail_quote" style="margin:0px 0px 0px 0.8ex;border-left:1px solid rgb(204,204,204);padding-left:1ex">';
  var GMAIL_SIGNATURE_PREFIX = '<span class="gmail_signature_prefix">-- </span><br>';
  function signatureText(sig) {
    return wrapText(sig.text?.trim() || htmlToText(sig.html));
  }
  function signatureBlockNew(sig) {
    return `${GMAIL_SIGNATURE_PREFIX}<div dir="ltr" class="gmail_signature" data-smartmail="gmail_signature">${sig.html}</div>`;
  }
  function signatureBlockAfterQuote(sig, smartmail) {
    const attr = smartmail ? ' data-smartmail="gmail_signature"' : "";
    return `<div><br clear="all"></div><div><br></div>${GMAIL_SIGNATURE_PREFIX}<div dir="ltr" class="gmail_signature"${attr}>${sig.html}</div>`;
  }
  function signatureBlockBeforeQuote(sig) {
    return `<div><br></div><div><div dir="ltr" class="gmail_signature" data-smartmail="gmail_signature">${sig.html}</div></div>`;
  }
  function quoteBlockHtml(attrInner, originalHtml) {
    return `<div class="gmail_quote gmail_quote_container"><div dir="ltr" class="gmail_attr">${attrInner}<br></div>${GMAIL_BLOCKQUOTE_OPEN}${originalHtml}</blockquote></div>`;
  }
  function originalHtmlFor(original) {
    if (original.html) return neutralizeUnbalancedTags(original.html);
    if (original.text) return escapeHtml(original.text).replace(/\r?\n/g, "<br>");
    return "";
  }
  function originalTextFor(original, opts) {
    if (opts.quoteTextSource === "convert-html" && original.html) return wrapText(htmlToText(original.html));
    if (original.text) return original.text.replace(/\r\n?/g, "\n").replace(/\s+$/, "");
    if (original.html) return wrapText(htmlToText(original.html));
    return "";
  }
  function wrapForwardedOriginal(html, seed) {
    const n = seed ?? String(Math.floor(Math.random() * 9e17) + 1e17);
    const prefixed = html.replace(/\bid="([^"]*)"/g, (_m, id) => `id="m_-${n}${id}"`);
    return `<div class="msg-${n}">${prefixed}</div>`;
  }
  function dateOpts(opts) {
    return { timeZone: opts.timeZone, amPmSeparator: opts.amPmSeparator };
  }
  function myEmails(opts) {
    return opts.myEmails?.length ? opts.myEmails : [opts.from.email];
  }
  function threadRefs(original) {
    if (!original.messageId) return {};
    const refs = uniqueStrings([...original.references ?? [], original.messageId]);
    return { inReplyTo: original.messageId, references: refs };
  }
  function uniqueStrings(list) {
    return Array.from(new Set(list.filter(Boolean)));
  }
  function composeNew(input, opts) {
    const sig = opts.signature ?? null;
    const bodyHtml = textToGmailHtml(input.body, "new");
    const html = `<div dir="ltr">${bodyHtml}${sig ? `<div><br></div>${signatureBlockNew(sig)}` : ""}</div>\r
`;
    const bodyText = wrapText(input.body.trim());
    const text = sig ? `${bodyText}

--
${signatureText(sig)}` : bodyText;
    return {
      mode: "new",
      subject: input.subject.trim(),
      from: opts.from,
      to: uniqueAddresses(input.to),
      cc: uniqueAddresses(input.cc ?? []),
      bcc: uniqueAddresses(input.bcc ?? []),
      html,
      text,
      attachments: input.attachments
    };
  }
  function composeReply(original, input, opts) {
    const sig = opts.signature ?? null;
    const placement = opts.signaturePlacement ?? "after-quote";
    const d = dateOpts(opts);
    const attrInner = attributionHtml(original, { ...d, linkifyEmail: opts.linkifyAttributionEmail });
    const quote = quoteBlockHtml(attrInner, originalHtmlFor(original));
    const bodyHtml = textToGmailHtml(input.body, "reply");
    let html;
    if (sig && placement === "before-quote") {
      html = `<div dir="ltr">${bodyHtml}${signatureBlockBeforeQuote(sig)}</div><br>${quote}\r
`;
    } else {
      html = `<div dir="ltr">${bodyHtml}</div><br>${quote}${sig ? signatureBlockAfterQuote(sig, false) : ""}\r
`;
    }
    const bodyText = wrapText(input.body.trim());
    const quotedText = quoteText(originalTextFor(original, opts));
    const attrText = attributionText(original, { ...d, linkifyEmail: opts.linkifyAttributionEmail });
    let text;
    if (sig && placement === "before-quote") {
      text = `${bodyText}

${signatureText(sig)}

${attrText}

${quotedText}
`;
    } else {
      text = `${bodyText}

${attrText}

${quotedText}
${sig ? `
--
${signatureText(sig)}` : ""}`;
    }
    const computed = replyRecipients(original, myEmails(opts), !!input.replyAll);
    const to = uniqueAddresses(input.to ?? computed.to);
    const cc = withoutAddresses(uniqueAddresses([...input.cc ?? computed.cc, ...input.addCc ?? []]), to);
    const bcc = withoutAddresses(uniqueAddresses([...input.bcc ?? [], ...input.addBcc ?? []]), [...to, ...cc]);
    return {
      mode: "reply",
      subject: replySubject(original.subject),
      from: opts.from,
      to,
      cc,
      bcc,
      html,
      text,
      threadId: original.threadId,
      ...threadRefs(original),
      attachments: input.attachments,
      originalMessageId: original.id
    };
  }
  function composeForward(original, input, opts) {
    const sig = opts.signature ?? null;
    const placement = opts.signaturePlacement ?? "after-quote";
    const d = dateOpts(opts);
    const body = (input.body ?? "").trim();
    const bodyHtml = body ? textToGmailHtml(body, "reply") : "";
    const header = forwardHeaderHtml(original, d);
    const forwarded = `<div class="gmail_quote gmail_quote_container"><div dir="ltr" class="gmail_attr">${header}</div><br><br>${wrapForwardedOriginal(originalHtmlFor(original), input.forwardSeed)}</div>`;
    let html;
    if (sig && placement === "before-quote") {
      html = `<div dir="ltr">${bodyHtml}${signatureBlockBeforeQuote(sig)}<br><br>${forwarded}</div>\r
`;
    } else {
      html = `<div dir="ltr">${bodyHtml}<br><br>${forwarded}${sig ? signatureBlockAfterQuote(sig, true) : ""}</div>\r
`;
    }
    const origText = originalTextFor(original, opts);
    const headerText = forwardHeaderText(original, d);
    let text;
    if (sig && placement === "before-quote") {
      text = `${body ? wrapText(body) + "\n\n" : ""}${signatureText(sig)}


${headerText}

${origText}`;
    } else {
      text = `${body ? wrapText(body) + "\n\n\n" : ""}${headerText}

${origText}${sig ? `

--
${signatureText(sig)}` : ""}`;
    }
    const includeAttachments = input.includeAttachments ?? true;
    return {
      mode: "forward",
      subject: forwardSubject(original.subject),
      from: opts.from,
      to: uniqueAddresses(input.to),
      cc: uniqueAddresses(input.cc ?? []),
      bcc: uniqueAddresses(input.bcc ?? []),
      html,
      text,
      threadId: original.threadId,
      attachments: includeAttachments ? original.attachments : void 0,
      originalMessageId: original.id
    };
  }

  // src/core/encoding.ts
  var hasBuffer = typeof Buffer !== "undefined" && typeof Buffer.from === "function";
  function utf8Encode(s) {
    if (hasBuffer) return new Uint8Array(Buffer.from(s, "utf8"));
    if (typeof TextEncoder !== "undefined") return new TextEncoder().encode(s);
    const out = [];
    for (let i = 0; i < s.length; i++) {
      let c = s.charCodeAt(i);
      if (c >= 55296 && c <= 56319 && i + 1 < s.length) {
        const d = s.charCodeAt(i + 1);
        if (d >= 56320 && d <= 57343) {
          c = 65536 + (c - 55296 << 10) + (d - 56320);
          i++;
        }
      }
      if (c < 128) out.push(c);
      else if (c < 2048) out.push(192 | c >> 6, 128 | c & 63);
      else if (c < 65536) out.push(224 | c >> 12, 128 | c >> 6 & 63, 128 | c & 63);
      else out.push(240 | c >> 18, 128 | c >> 12 & 63, 128 | c >> 6 & 63, 128 | c & 63);
    }
    return Uint8Array.from(out);
  }
  function utf8Decode(bytes) {
    if (hasBuffer) return Buffer.from(bytes).toString("utf8");
    if (typeof TextDecoder !== "undefined") return new TextDecoder().decode(bytes);
    let out = "";
    for (let i = 0; i < bytes.length; ) {
      const b = bytes[i];
      let cp;
      let n;
      if (b < 128) {
        cp = b;
        n = 1;
      } else if ((b & 224) === 192) {
        cp = b & 31;
        n = 2;
      } else if ((b & 240) === 224) {
        cp = b & 15;
        n = 3;
      } else {
        cp = b & 7;
        n = 4;
      }
      for (let k = 1; k < n; k++) cp = cp << 6 | bytes[i + k] & 63;
      out += String.fromCodePoint(cp);
      i += n;
    }
    return out;
  }
  var B64 = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
  function base64Encode(bytes) {
    if (hasBuffer) return Buffer.from(bytes).toString("base64");
    let out = "";
    for (let i = 0; i < bytes.length; i += 3) {
      const a = bytes[i];
      const b = i + 1 < bytes.length ? bytes[i + 1] : NaN;
      const c = i + 2 < bytes.length ? bytes[i + 2] : NaN;
      out += B64[a >> 2];
      out += B64[(a & 3) << 4 | (isNaN(b) ? 0 : b >> 4)];
      out += isNaN(b) ? "=" : B64[(b & 15) << 2 | (isNaN(c) ? 0 : c >> 6)];
      out += isNaN(c) ? "=" : B64[c & 63];
    }
    return out;
  }
  function base64Decode(s) {
    const clean = s.replace(/-/g, "+").replace(/_/g, "/").replace(/[^A-Za-z0-9+/]/g, "");
    if (hasBuffer) return new Uint8Array(Buffer.from(clean, "base64"));
    const out = [];
    let bits = 0;
    let acc = 0;
    for (const ch of clean) {
      acc = acc << 6 | B64.indexOf(ch);
      bits += 6;
      if (bits >= 8) {
        bits -= 8;
        out.push(acc >> bits & 255);
      }
    }
    return Uint8Array.from(out);
  }
  function randomHex(chars) {
    const g = globalThis.crypto;
    if (g && typeof g.getRandomValues === "function") {
      const arr = new Uint8Array(Math.ceil(chars / 2));
      g.getRandomValues(arr);
      return Array.from(arr, (b) => b.toString(16).padStart(2, "0")).join("").slice(0, chars);
    }
    let out = "";
    while (out.length < chars) out += Math.floor(Math.random() * 16).toString(16);
    return out;
  }
  function randomAlnum(chars) {
    const alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
    const hex = randomHex(chars * 2);
    let out = "";
    for (let i = 0; i < chars; i++) out += alphabet[parseInt(hex.slice(i * 2, i * 2 + 2), 16) % alphabet.length];
    return out;
  }

  // src/core/mime.ts
  function gmailBoundary() {
    return "000000000000" + randomHex(12);
  }
  function headerValue(value, field) {
    if (/[\r\n]/.test(value)) {
      throw new Error(`Illegal line break in ${field}. Header values cannot contain a carriage return or line feed.`);
    }
    return value;
  }
  function buildMime(msg, opts = {}) {
    const date = opts.date ?? /* @__PURE__ */ new Date();
    const altBoundary = opts.boundary ?? gmailBoundary();
    const headers = [];
    headers.push("MIME-Version: 1.0");
    headers.push(`Date: ${formatRfc2822Date(date, opts.timeZone)}`);
    if (opts.messageId) headers.push(`Message-ID: ${headerValue(opts.messageId, "Message-ID")}`);
    headers.push(`Subject: ${encodeHeaderText(msg.subject)}`);
    headers.push(`From: ${encodeAddressHeader([msg.from], "From")}`);
    if (msg.to.length) headers.push(`To: ${encodeAddressHeader(msg.to, "To")}`);
    if (msg.cc.length) headers.push(`Cc: ${encodeAddressHeader(msg.cc, "Cc")}`);
    if (msg.bcc.length) headers.push(`Bcc: ${encodeAddressHeader(msg.bcc, "Bcc")}`);
    if (msg.inReplyTo) headers.push(`In-Reply-To: ${headerValue(msg.inReplyTo, "In-Reply-To")}`);
    if (msg.references?.length) headers.push(`References: ${msg.references.map((r) => headerValue(r, "References")).join(" ")}`);
    const alternative = [
      `--${altBoundary}`,
      'Content-Type: text/plain; charset="UTF-8"',
      "Content-Transfer-Encoding: quoted-printable",
      "",
      // The CRLF before each boundary line belongs to the delimiter (RFC 2046), so the
      // part content is exactly the encoded text, nothing appended.
      quotedPrintable(msg.text),
      `--${altBoundary}`,
      'Content-Type: text/html; charset="UTF-8"',
      "Content-Transfer-Encoding: quoted-printable",
      "",
      quotedPrintable(msg.html),
      `--${altBoundary}--`
    ].join("\r\n");
    const attachments = (msg.attachments ?? []).filter((a) => a.data);
    if (!attachments.length) {
      headers.push(`Content-Type: multipart/alternative; boundary="${altBoundary}"`);
      return headers.join("\r\n") + "\r\n\r\n" + alternative + "\r\n";
    }
    const mixedBoundary = gmailBoundary();
    headers.push(`Content-Type: multipart/mixed; boundary="${mixedBoundary}"`);
    const parts = [];
    parts.push(`--${mixedBoundary}\r
Content-Type: multipart/alternative; boundary="${altBoundary}"\r
\r
${alternative}`);
    for (const a of attachments) {
      parts.push(
        [
          `--${mixedBoundary}`,
          `Content-Type: ${headerValue(a.mimeType, "attachment mimeType")}; name="${headerValue(a.filename, "attachment filename")}"`,
          `Content-Disposition: attachment; filename="${headerValue(a.filename, "attachment filename")}"`,
          "Content-Transfer-Encoding: base64",
          "",
          foldBase64(a.data)
        ].join("\r\n")
      );
    }
    parts.push(`--${mixedBoundary}--`);
    return headers.join("\r\n") + "\r\n\r\n" + parts.join("\r\n") + "\r\n";
  }
  function foldBase64(b64) {
    return b64.replace(/\s+/g, "").match(/.{1,76}/g)?.join("\r\n") ?? "";
  }
  var rfc2822Formatter = null;
  function setRfc2822Formatter(fn) {
    rfc2822Formatter = fn;
  }
  function formatRfc2822Date(date, timeZone) {
    const tz = timeZone ?? "UTC";
    if (rfc2822Formatter) return rfc2822Formatter(date, tz);
    const parts = new Intl.DateTimeFormat("en-US", {
      weekday: "short",
      day: "2-digit",
      month: "short",
      year: "numeric",
      hour: "2-digit",
      minute: "2-digit",
      second: "2-digit",
      hour12: false,
      timeZone: tz,
      timeZoneName: "longOffset"
    }).formatToParts(date);
    const get = (t) => parts.find((p) => p.type === t)?.value ?? "";
    const off = get("timeZoneName");
    const m = off.match(/([+-])(\d{2}):(\d{2})/);
    const offset = m ? `${m[1]}${m[2]}${m[3]}` : "+0000";
    const hour = get("hour") === "24" ? "00" : get("hour");
    return `${get("weekday")}, ${get("day")} ${get("month")} ${get("year")} ${hour}:${get("minute")}:${get("second")} ${offset}`;
  }
  function encodeHeaderText(s) {
    if (!/[^\x20-\x7e]/.test(s)) return s;
    return `=?UTF-8?B?${base64Encode(utf8Encode(s))}?=`;
  }
  function encodeAddressHeader(list, field) {
    return list.map((a) => {
      const email = headerValue(a.email, `${field} address`);
      if (a.name && /[^\x20-\x7e]/.test(a.name)) return `${encodeHeaderText(a.name)} <${email}>`;
      return formatAddress({ ...a, email });
    }).join(", ");
  }
  function quotedPrintable(input) {
    const normalized = input.replace(/\r\n?|\n/g, "\r\n");
    const bytes = utf8Encode(normalized);
    let out = "";
    let lineLen = 0;
    for (let i = 0; i < bytes.length; i++) {
      const b = bytes[i];
      if (b === 13 && bytes[i + 1] === 10) {
        out += "\r\n";
        lineLen = 0;
        i++;
        continue;
      }
      const atLineEnd = i + 1 >= bytes.length || bytes[i + 1] === 13 && bytes[i + 2] === 10;
      let token;
      if (b >= 33 && b <= 126 && b !== 61 || (b === 32 || b === 9) && !atLineEnd) {
        token = String.fromCharCode(b);
      } else {
        token = "=" + b.toString(16).toUpperCase().padStart(2, "0");
      }
      if (lineLen + token.length > 75) {
        out += "=\r\n";
        lineLen = 0;
      }
      out += token;
      lineLen += token.length;
    }
    return out;
  }
  function decodeQuotedPrintable(input) {
    const joined = input.replace(/=\r?\n/g, "");
    const bytes = [];
    for (let i = 0; i < joined.length; i++) {
      const ch = joined[i];
      if (ch === "=" && /^[0-9A-Fa-f]{2}$/.test(joined.slice(i + 1, i + 3))) {
        bytes.push(parseInt(joined.slice(i + 1, i + 3), 16));
        i += 2;
      } else bytes.push(ch.charCodeAt(0) & 255);
    }
    return utf8Decode(Uint8Array.from(bytes));
  }
  function base64Url(s) {
    return base64Encode(utf8Encode(s)).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
  }
  function fromBase64Url(s) {
    return utf8Decode(base64Decode(s));
  }
  function gmailMessageId() {
    return `<CA+${randomAlnum(16)}=${randomAlnum(32)}@mail.gmail.com>`;
  }
  return __toCommonJS(browser_exports);
})();
